### ISSUE TITLE
blog post on Song Lyrics Across the United States

### ISSUE THREAD

**Issue by benmarwick** [juliasilge/juliasilge.github.io#1]
Hi Julia, my friend Matt Harris and I have been looking at your wonderful post on 'Song Lyrics Across the United States' (we're great fans of your work with R!). Your R posts have been very helpful for us to get a better understanding of dplyr. We were wondering if it might be possible that your counts are slight underestimates due to undercounting songs that mention more than one state? 

Matt and I had a bit of a look at this in a gist here: https://gist.github.com/benmarwick/4c0ba8f76bcaa4ed35b7fc18bd2f8d70. 

Could it be that `distinct()` should include `state_name` to count songs that have more than one state name in their lyrics? 

It'a a small detail, and doesn't change your results in any major way. But we just wanted to make sure we could follow what you were doing, and unobtrusively check if we understood correctly what you've done. Look forward to hearing from you!

**Comment by juliasilge** [comment]
Ah, you are right! I just opened this data back up and this is exactly correct. Really good catch, and what excellent relational database thinking. Thanks so much for sharing your work. :raised_hands:

**Comment by benmarwick** [comment]
Thanks for taking a look! Just wanted to make sure I was understanding your analysis correctly :)
